set-option -g prefix C-a
unbind-key C-b
bind-key a send-prefix

set -g default-terminal screen-256color
set -g history-limit 5000
set -g renumber-windows on
setw -g mode-keys vi

bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xclip -in -sel clip"
bind-key Tab select-pane -t :.+ 
bind -n M-Escape copy-mode

set -g status-position top
set -g status-left " "
set -g status-right "#h "
set -g window-status-format "-"
set -g window-status-current-format "*"

set -g status-style reverse,bright
set -g message-style reverse
set -g mode-style bg=cyan,fg=default
