# use control+a as a prefix like screen
set-option -g prefix C-a
unbind-key C-b
bind-key a send-prefix

set -g status-position top
set -g history-limit 50000

# colors hurt my eyes
set -g status-style reverse,bright
set -g message-style reverse
